### ISSUE TITLE
About the C3D feature

### ISSUE THREAD

**Issue by mengliu1991** [jiyanggao/TALL#1]
Hi, 

  I download the feature extraction file from the c3d GitHub web, but I find that they can only extract features for 16 frames.
 Can you provide your retrain C3D model ( 128 frames, 64 frames, 256 frames) for TALL dataset for me?

**Comment by jiyanggao** [comment]
Hi, I didn't retrain the C3D model. I just uniformly sample 16 frames from the 128 frames, and input them into the C3D.

**Comment by h-bo** [comment]
So you mean you feed them separately and mean the feats at last as feat of 128 frames?

**Comment by h-bo** [comment]
Can you give me feat for per 16 frames? Thanks

**Comment by stha-prashant** [comment]
hello @h-bo, I'm looking for the same answer, did you find the c3d model used for feature extraction?
